name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: canonical/starflow/.github/workflows/lint-python.yaml@main
  test:
    uses: canonical/starflow/.github/workflows/test-python.yaml@main
    with:
      # Fast tests run on several Ubuntu platforms and macos on ARM
      fast-test-platforms: '["ubuntu-24.04", "ubuntu-24.04-arm", "macos-13"]'
      fast-test-python-versions: '["3.10", "3.12", "3.13"]'
      # Slow tests (which include everything that needs multipass) run on amd64 macos and several Ubuntu platforms
      slow-test-platforms: '["ubuntu-24.04", "ubuntu-24.04-arm", "macos-13"]'
      slow-test-python-versions: '["3.12"]'
      lowest-python-platform: "ubuntu-22.04"
      lowest-python-version: "3.10"
      use-lxd: true
