name: TICS

on:
  push:
    branches:
    - main
    # to easy test changes to the workflow
    - tiobe

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          echo "::group::apt-get update"
          sudo apt-get update
          echo "::endgroup::"
          echo "::group::apt-get install..."
          sudo apt-get install -y python3 python3-dev libyaml-dev pylint flake8
          echo "::endgroup::"
          echo "::group::pip install"
          python -m pip install 'tox<5.0' tox-gh
          echo "::endgroup::"

      - name: Setup Tox environment
        run: tox run-parallel --parallel auto --parallel-no-spinner --parallel-live --colored yes -e unit-py3.10 --notest

      - name: Test with tox
        run: tox run --skip-pkg-install --result-json results/tox-py310.json --colored yes -e unit-py3.10

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-ubuntu-22.04
          path: results/

      # Uncomment when the project is setup
      #      - name: Run TICS analysis
      #        uses: tiobe/tics-github-action@v3
      #        with:
      #          mode: qserver
      #          project: craft-providers
      #          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
      #          branchdir: ${{ github.workspace }}
      #          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
      #          installTics: true
